name = "Jurisdictions"
uuid = "044ac1b0-3745-11e9-192d-5d2cecb87306"
authors = ["Eric Forgy <Eric.Forgy@coherentasia.com>"]
version = "0.1.0"

[deps]
Markets = "b44f5480-3750-11e9-03b7-d5e34f572a03"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
